// Lista blanca de canales IPC. Este archivo NO importa zod: lo usa el preload (sandbox),
// que sólo puede bundlear código chico y sin dependencias pesadas.
// Un test verifica que coincida con las claves de `ipcContract`.
export const IPC_CHANNELS = [
  'app:ping',
  'app:info',
  'catalog:list',
  'catalog:createCategory',
  'catalog:updateCategory',
  'catalog:archiveCategory',
  'catalog:reorderCategories',
  'catalog:createSubcategory',
  'catalog:renameSubcategory',
  'catalog:archiveSubcategory',
  'catalog:reorderSubcategories',
  'paymentMethods:list',
  'paymentMethods:create',
  'paymentMethods:update',
  'paymentMethods:archive',
  'paymentMethods:reorder',
  'groups:list',
  'groups:create',
  'groups:update',
  'groups:archive',
  'month:overview',
  'expenses:create',
  'expenses:update',
  'expenses:setAmount',
  'expenses:duplicate',
  'expenses:remove',
  'expenses:restore',
  'expenses:search',
  'plans:create',
  'plans:get',
  'plans:update',
  'plans:remove',
  'recurring:list',
  'recurring:create',
  'recurring:update',
  'recurring:remove',
  'incomes:list',
  'incomes:create',
  'incomes:update',
  'incomes:remove',
  'incomes:restore',
  'incomes:copyPreviousSalary',
  'cards:overview',
  'savings:overview',
  'savings:createMovement',
  'savings:updateMovement',
  'savings:removeMovement',
  'savings:restoreMovement',
  'savings:createGoal',
  'savings:updateGoal',
  'savings:archiveGoal',
  'report:year',
  'export:run',
  'export:reveal',
  'backups:list',
  'backups:create',
  'backups:openFolder',
  'backups:restore',
  'backups:restoreFromFile',
] as const

export type IpcChannel = (typeof IPC_CHANNELS)[number]

export function isIpcChannel(value: unknown): value is IpcChannel {
  return typeof value === 'string' && (IPC_CHANNELS as readonly string[]).includes(value)
}
