import { expect, test } from './fixtures'

test('armar un grupo y cargar un gasto eligiendo quién pagó', async ({ page }) => {
  await page.getByRole('link', { name: 'Configuración' }).click()
  await page.getByRole('tab', { name: 'Grupos' }).click()
  await expect(page.getByText('Todavía no armaste ningún grupo.')).toBeVisible()

  await page.getByRole('button', { name: 'Grupo', exact: true }).click()
  const groupDialog = page.getByRole('dialog')
  await groupDialog.locator('#group-name').fill('Casa')
  await groupDialog.getByLabel('Persona 1').fill('Tobi')
  await groupDialog.getByLabel('Persona 2').fill('Ana')
  await groupDialog.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByText('Grupo creado')).toBeVisible()
  await expect(page.getByText('Tobi, Ana')).toBeVisible()

  await page.keyboard.press('Control+n')
  const dialog = page.getByRole('dialog')
  await dialog.locator('#expense-amount').fill('40.000')
  await dialog.locator('#expense-category').click()
  await page.getByPlaceholder('Buscar…').fill('Chino')
  await page.keyboard.press('Enter')
  await dialog.locator('#expense-description').fill('Cena')
  await dialog.locator('#expense-group').click()
  await page.getByRole('option', { name: 'Casa' }).click()
  await expect(dialog.locator('#expense-payer')).toContainText('Tobi')
  await dialog.locator('#expense-payer').click()
  await page.getByRole('option', { name: 'Ana' }).click()
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Gasto guardado')).toBeVisible()

  await page.getByRole('link', { name: 'Inicio' }).click()
  const row = page.getByTestId('expense-row').filter({ hasText: 'Cena' })
  await expect(row).toContainText('Casa · pagó Ana')
})

test('repartir a mano, ver quién le debe a quién y saldar', async ({ page }) => {
  await page.getByRole('link', { name: 'Configuración' }).click()
  await page.getByRole('tab', { name: 'Grupos' }).click()
  await page.getByRole('button', { name: 'Grupo', exact: true }).click()
  const groupDialog = page.getByRole('dialog')
  await groupDialog.locator('#group-name').fill('Casa')
  await groupDialog.getByLabel('Persona 1').fill('Tobi')
  await groupDialog.getByLabel('Persona 2').fill('Ana')
  await groupDialog.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByText('Grupo creado')).toBeVisible()

  await page.keyboard.press('Control+n')
  const dialog = page.getByRole('dialog')
  await dialog.locator('#expense-amount').fill('30.000')
  await dialog.locator('#expense-category').click()
  await page.getByPlaceholder('Buscar…').fill('Chino')
  await page.keyboard.press('Enter')
  await dialog.locator('#expense-group').click()
  await page.getByRole('option', { name: 'Casa' }).click()
  await dialog.getByRole('radio', { name: 'A mano' }).click()
  await dialog.getByLabel('Parte de Tobi').fill('10.000')
  await expect(dialog.getByText('Faltan asignar $ 5.000')).toBeVisible()
  await dialog.getByLabel('Parte de Ana').fill('20.000')
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Gasto guardado')).toBeVisible()

  await page.getByRole('link', { name: 'Grupos' }).click()
  const card = page.getByTestId('group-card').filter({ hasText: 'Casa' })
  const transfer = card.getByTestId('group-transfer')
  await expect(transfer).toContainText('Ana')
  await expect(transfer).toContainText('Tobi')
  await expect(transfer).toContainText('$ 20.000')

  await transfer.getByRole('button', { name: 'Saldar' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Registrar pago' }).click()
  await expect(page.getByText('Pago registrado')).toBeVisible()
  await expect(card.getByText('Están a mano.')).toBeVisible()
  await expect(card.getByTestId('settlement')).toContainText('Ana le pasó a Tobi')
})
