import {
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Cat,
  Coffee,
  CreditCard,
  Dog,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Pill,
  Plane,
  PartyPopper,
  PiggyBank,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Tag,
  Ticket,
  TrainFront,
  Tv,
  Utensils,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Íconos disponibles para categorías (nombre de lucide en kebab-case → componente). */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  house: House,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  utensils: Utensils,
  coffee: Coffee,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  'party-popper': PartyPopper,
  ticket: Ticket,
  'gamepad-2': Gamepad2,
  tv: Tv,
  'heart-pulse': HeartPulse,
  pill: Pill,
  dumbbell: Dumbbell,
  sofa: Sofa,
  hammer: Hammer,
  wrench: Wrench,
  shirt: Shirt,
  scissors: Scissors,
  sparkles: Sparkles,
  landmark: Landmark,
  'credit-card': CreditCard,
  banknote: Banknote,
  receipt: Receipt,
  'piggy-bank': PiggyBank,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  'train-front': TrainFront,
  bike: Bike,
  plane: Plane,
  smartphone: Smartphone,
  laptop: Laptop,
  wifi: Wifi,
  zap: Zap,
  briefcase: Briefcase,
  gift: Gift,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  tag: Tag,
}

/** Paleta suave para categorías y medios de pago. */
export const PALETTE = [
  '#6366f1',
  '#8b5cf6',
  '#ec4899',
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#84cc16',
  '#10b981',
  '#14b8a6',
  '#0ea5e9',
  '#3b82f6',
  '#64748b',
]

export function iconFor(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? Tag
}
